# Generated by Django 3.0.5 on 2020-04-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
